// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using WatchKit;

namespace WatchExtension
{
	public partial class TweetController : WKInterfaceController
	{
		public TweetController (IntPtr handle) : base (handle)
		{
		}

		public override void Awake (NSObject context)
		{
			base.Awake (context);

			var id = ((NSNumber)context).NIntValue;

			var tweet = InterfaceController.Tweets [(int)id];

			TweetText.SetText (tweet.Text);
      TweetDate.SetText(tweet.Date);
		}
	}
}
