#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Hanselman.Android.Resource", IsApplication=true)]

namespace Hanselman.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blog = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int facebook = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int googleplus = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int instagram = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int refresh = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int scott = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int slideout = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int twitter = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int twitternav = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int myButton = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MyTheme = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int MyTheme_ActionBar_TitleTextStyle = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int MyTheme_ActionBarStyle = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
