#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WearApp.Resource", IsApplication=true)]

namespace WearApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int generic_confirmation_generic_confirmation_animation = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int generic_confirmation_icon_animation = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int open_on_phone_arrow_animation = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int open_on_phone_path_1_animation = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int open_on_phone_path_2_animation = 2130968580;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f050000
			public const int circular_image_button_anim = 2131034112;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0a0000
			public const int progress_spinner_sequence = 2131361792;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010011
			public const int buttonRippleColor = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int circle_border_color = 2130771978;
			
			// aapt resource value: 0x7f010009
			public const int circle_border_width = 2130771977;
			
			// aapt resource value: 0x7f010006
			public const int circle_color = 2130771974;
			
			// aapt resource value: 0x7f01000b
			public const int circle_padding = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int circle_radius = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int circle_radius_pressed = 2130771976;
			
			// aapt resource value: 0x7f01002c
			public const int circular_layout_gravity = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int circular_text_size = 2130772013;
			
			// aapt resource value: 0x7f010021
			public const int color_sequence = 2130772001;
			
			// aapt resource value: 0x7f010017
			public const int dotColor = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int dotColorSelected = 2130771992;
			
			// aapt resource value: 0x7f01001c
			public const int dotFadeInDuration = 2130771996;
			
			// aapt resource value: 0x7f01001a
			public const int dotFadeOutDelay = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int dotFadeOutDuration = 2130771995;
			
			// aapt resource value: 0x7f010019
			public const int dotFadeWhenIdle = 2130771993;
			
			// aapt resource value: 0x7f010015
			public const int dotRadius = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int dotRadiusSelected = 2130771990;
			
			// aapt resource value: 0x7f01001d
			public const int dotShadowColor = 2130771997;
			
			// aapt resource value: 0x7f01001f
			public const int dotShadowDx = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int dotShadowDy = 2130772000;
			
			// aapt resource value: 0x7f01001e
			public const int dotShadowRadius = 2130771998;
			
			// aapt resource value: 0x7f010014
			public const int dotSpacing = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010010
			public const int imageScaleMode = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public const int image_circle_percentage = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int image_horizontal_offcenter_percentage = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int image_tint = 2130771983;
			
			// aapt resource value: 0x7f01002e
			public const int layoutManager = 2130772014;
			
			// aapt resource value: 0x7f010005
			public const int layout_box = 2130771973;
			
			// aapt resource value: 0x7f010024
			public const int layout_gravityRound = 2130772004;
			
			// aapt resource value: 0x7f010026
			public const int layout_heightRound = 2130772006;
			
			// aapt resource value: 0x7f01002b
			public const int layout_marginBottomRound = 2130772011;
			
			// aapt resource value: 0x7f010028
			public const int layout_marginLeftRound = 2130772008;
			
			// aapt resource value: 0x7f01002a
			public const int layout_marginRightRound = 2130772010;
			
			// aapt resource value: 0x7f010027
			public const int layout_marginRound = 2130772007;
			
			// aapt resource value: 0x7f010029
			public const int layout_marginTopRound = 2130772009;
			
			// aapt resource value: 0x7f010025
			public const int layout_widthRound = 2130772005;
			
			// aapt resource value: 0x7f010004
			public const int maxTextSize = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int minTextSize = 2130771971;
			
			// aapt resource value: 0x7f010012
			public const int pressedButtonTranslationZ = 2130771986;
			
			// aapt resource value: 0x7f010022
			public const int rectLayout = 2130772002;
			
			// aapt resource value: 0x7f010030
			public const int reverseLayout = 2130772016;
			
			// aapt resource value: 0x7f010023
			public const int roundLayout = 2130772003;
			
			// aapt resource value: 0x7f01000c
			public const int shadow_width = 2130771980;
			
			// aapt resource value: 0x7f01002f
			public const int spanCount = 2130772015;
			
			// aapt resource value: 0x7f010031
			public const int stackFromEnd = 2130772017;
			
			// aapt resource value: 0x7f010013
			public const int update_interval = 2130771987;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f08000a
			public const int action_button_background = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int black = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int black_54p = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int black_86p = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int blue = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int card_default_background = 2131230735;
			
			// aapt resource value: 0x7f080026
			public const int circular_button = 2131230758;
			
			// aapt resource value: 0x7f080010
			public const int circular_button_disabled = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int circular_button_normal = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int circular_button_pressed = 2131230738;
			
			// aapt resource value: 0x7f080009
			public const int common_action_bar_splitter = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int common_signin_btn_dark_text_default = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int common_signin_btn_dark_text_disabled = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int common_signin_btn_dark_text_focused = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int common_signin_btn_dark_text_pressed = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int common_signin_btn_default_background = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int common_signin_btn_light_text_default = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int common_signin_btn_light_text_disabled = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int common_signin_btn_light_text_focused = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int common_signin_btn_light_text_pressed = 2131230725;
			
			// aapt resource value: 0x7f080027
			public const int common_signin_btn_text_dark = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int common_signin_btn_text_light = 2131230760;
			
			// aapt resource value: 0x7f080013
			public const int dark_blue = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int dark_grey = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int dark_red = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int dialog_background = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int dialog_shade_background = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int disabled_text_light = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int dismiss_close = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int dismiss_close_pressed = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int dismiss_overlay_bg = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int green = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int grey = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int light_grey = 2131230750;
			
			// aapt resource value: 0x7f08001f
			public const int orange = 2131230751;
			
			// aapt resource value: 0x7f080020
			public const int primary_text_dark = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int primary_text_light = 2131230753;
			
			// aapt resource value: 0x7f080022
			public const int red = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int secondary_text_light = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int semitransparent_grey = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int white = 2131230757;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0b0000
			public const int card_content_padding_rect_top = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int circular_button_elevation = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int circular_button_elevation_pressed = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int close_button_diameter = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int diag_button_bottom_padding = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int diag_button_bottom_padding_round = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int diag_button_side_padding_right_round = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int diag_content_bottom_padding = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int diag_content_side_padding = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int diag_content_side_padding_round = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int diag_content_top_padding = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int diag_content_top_padding_round = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int diag_floating_height = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int diag_shade_height_rect = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int diag_shade_height_round = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int dismiss_padding = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131427344;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int card_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int card_frame = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int card_frame_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int close_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_full_open_on_phone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_ic_googleplayservices = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_disabled_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_disabled_focus_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_disabled_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_focus_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_focus_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_normal_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_normal_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_pressed_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_icon_pressed_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_disabled_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_disabled_focus_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_disabled_focus_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_disabled_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_focus_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_focus_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_normal_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_normal_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_pressed_dark = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_text_pressed_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int generic_confirmation = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int generic_confirmation_animation = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_full_cancel = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_full_sad = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_launcher = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int open_on_phone = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int open_on_phone_animation = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int scott = 2130837541;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0d0001
			public const int adjust_height = 2131558401;
			
			// aapt resource value: 0x7f0d0002
			public const int adjust_width = 2131558402;
			
			// aapt resource value: 0x7f0d0016
			public const int alertTitle = 2131558422;
			
			// aapt resource value: 0x7f0d0004
			public const int all = 2131558404;
			
			// aapt resource value: 0x7f0d0015
			public const int animatedWrapperContainer = 2131558421;
			
			// aapt resource value: 0x7f0d0005
			public const int bottom = 2131558405;
			
			// aapt resource value: 0x7f0d001b
			public const int box_inset = 2131558427;
			
			// aapt resource value: 0x7f0d0017
			public const int buttonPanel = 2131558423;
			
			// aapt resource value: 0x7f0d0009
			public const int center = 2131558409;
			
			// aapt resource value: 0x7f0d000b
			public const int center_horizontal = 2131558411;
			
			// aapt resource value: 0x7f0d000c
			public const int center_vertical = 2131558412;
			
			// aapt resource value: 0x7f0d000d
			public const int clip_horizontal = 2131558413;
			
			// aapt resource value: 0x7f0d000e
			public const int clip_vertical = 2131558414;
			
			// aapt resource value: 0x7f0d0019
			public const int dismiss_overlay_button = 2131558425;
			
			// aapt resource value: 0x7f0d0018
			public const int dismiss_overlay_explain = 2131558424;
			
			// aapt resource value: 0x7f0d000f
			public const int end = 2131558415;
			
			// aapt resource value: 0x7f0d0010
			public const int fill = 2131558416;
			
			// aapt resource value: 0x7f0d0011
			public const int fill_horizontal = 2131558417;
			
			// aapt resource value: 0x7f0d0012
			public const int fill_vertical = 2131558418;
			
			// aapt resource value: 0x7f0d000a
			public const int fit = 2131558410;
			
			// aapt resource value: 0x7f0d0000
			public const int item_touch_helper_previous_elevation = 2131558400;
			
			// aapt resource value: 0x7f0d0006
			public const int left = 2131558406;
			
			// aapt resource value: 0x7f0d001a
			public const int message = 2131558426;
			
			// aapt resource value: 0x7f0d0003
			public const int none = 2131558403;
			
			// aapt resource value: 0x7f0d001c
			public const int pager = 2131558428;
			
			// aapt resource value: 0x7f0d0014
			public const int parentPanel = 2131558420;
			
			// aapt resource value: 0x7f0d001d
			public const int progressBar = 2131558429;
			
			// aapt resource value: 0x7f0d0007
			public const int right = 2131558407;
			
			// aapt resource value: 0x7f0d0013
			public const int start = 2131558419;
			
			// aapt resource value: 0x7f0d001f
			public const int text = 2131558431;
			
			// aapt resource value: 0x7f0d001e
			public const int title = 2131558430;
			
			// aapt resource value: 0x7f0d0008
			public const int top = 2131558408;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int google_play_services_version = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Interpolator
		{
			
			// aapt resource value: 0x7f060000
			public const int generic_confirmation_animation_interpolator_0 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int generic_confirmation_animation_interpolator_1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int generic_confirmation_animation_interpolator_2 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int generic_confirmation_animation_interpolator_3 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int open_on_phone_animation_interpolator_0 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int open_on_phone_animation_interpolator_1 = 2131099653;
			
			static Interpolator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Interpolator()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int alert_dialog_wearable = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dismiss_overlay = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int error_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int watch_card_content = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070023
			public const int app_name = 2131165219;
			
			// aapt resource value: 0x7f070001
			public const int auth_google_play_services_client_facebook_display_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int auth_google_play_services_client_google_display_name = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int common_android_wear_notification_needs_update_text = 2131165188;
			
			// aapt resource value: 0x7f070011
			public const int common_android_wear_update_text = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int common_android_wear_update_title = 2131165199;
			
			// aapt resource value: 0x7f07001f
			public const int common_google_play_services_api_unavailable_text = 2131165215;
			
			// aapt resource value: 0x7f07000d
			public const int common_google_play_services_enable_button = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_play_services_enable_text = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_play_services_enable_title = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int common_google_play_services_error_notification_requested_by_msg = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_play_services_install_button = 2131165194;
			
			// aapt resource value: 0x7f070008
			public const int common_google_play_services_install_text_phone = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int common_google_play_services_install_text_tablet = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int common_google_play_services_install_title = 2131165191;
			
			// aapt resource value: 0x7f070017
			public const int common_google_play_services_invalid_account_text = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int common_google_play_services_invalid_account_title = 2131165206;
			
			// aapt resource value: 0x7f070005
			public const int common_google_play_services_needs_enabling_title = 2131165189;
			
			// aapt resource value: 0x7f070015
			public const int common_google_play_services_network_error_text = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int common_google_play_services_network_error_title = 2131165204;
			
			// aapt resource value: 0x7f070003
			public const int common_google_play_services_notification_needs_update_title = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int common_google_play_services_notification_ticker = 2131165186;
			
			// aapt resource value: 0x7f070021
			public const int common_google_play_services_sign_in_failed_text = 2131165217;
			
			// aapt resource value: 0x7f070020
			public const int common_google_play_services_sign_in_failed_title = 2131165216;
			
			// aapt resource value: 0x7f070018
			public const int common_google_play_services_unknown_issue = 2131165208;
			
			// aapt resource value: 0x7f07001a
			public const int common_google_play_services_unsupported_text = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int common_google_play_services_unsupported_title = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int common_google_play_services_update_button = 2131165211;
			
			// aapt resource value: 0x7f070010
			public const int common_google_play_services_update_text = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int common_google_play_services_update_title = 2131165198;
			
			// aapt resource value: 0x7f070013
			public const int common_google_play_services_updating_text = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int common_google_play_services_updating_title = 2131165202;
			
			// aapt resource value: 0x7f07001e
			public const int common_open_on_phone = 2131165214;
			
			// aapt resource value: 0x7f07001c
			public const int common_signin_button_text = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int common_signin_button_text_long = 2131165213;
			
			// aapt resource value: 0x7f070022
			public const int dismiss_overlay_button_label = 2131165218;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0c0000
			public const int CardText = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int CardTitle = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int DismissOverlayText = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int DotsPageIndicatorStyle = 2131492867;
			
			// aapt resource value: 0x7f0c000f
			public const int TextAppearance_WearDiag = 2131492879;
			
			// aapt resource value: 0x7f0c0010
			public const int TextAppearance_WearDiag_Button = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int TextAppearance_WearDiag_Message = 2131492881;
			
			// aapt resource value: 0x7f0c0012
			public const int TextAppearance_WearDiag_Title = 2131492882;
			
			// aapt resource value: 0x7f0c0004
			public const int TextAppearance_Wearable_Large = 2131492868;
			
			// aapt resource value: 0x7f0c0005
			public const int TextAppearance_Wearable_Medium = 2131492869;
			
			// aapt resource value: 0x7f0c0006
			public const int TextAppearance_Wearable_Small = 2131492870;
			
			// aapt resource value: 0x7f0c0007
			public const int TextView_Large = 2131492871;
			
			// aapt resource value: 0x7f0c0008
			public const int TextView_Large_Light = 2131492872;
			
			// aapt resource value: 0x7f0c0009
			public const int TextView_Medium = 2131492873;
			
			// aapt resource value: 0x7f0c000a
			public const int TextView_Medium_Light = 2131492874;
			
			// aapt resource value: 0x7f0c000b
			public const int TextView_Small = 2131492875;
			
			// aapt resource value: 0x7f0c000c
			public const int TextView_Small_Light = 2131492876;
			
			// aapt resource value: 0x7f0c0013
			public const int Theme_WearDiag = 2131492883;
			
			// aapt resource value: 0x7f0c000d
			public const int Theme_Wearable = 2131492877;
			
			// aapt resource value: 0x7f0c000e
			public const int Theme_Wearable_Modal = 2131492878;
			
			// aapt resource value: 0x7f0c0014
			public const int Widget_ActionPage = 2131492884;
			
			// aapt resource value: 0x7f0c0015
			public const int Widget_WearDiag_Button = 2131492885;
			
			// aapt resource value: 0x7f0c0016
			public const int Widget_WearDiag_TextView = 2131492886;
			
			// aapt resource value: 0x7f0c0017
			public const int Widget_WearDiag_TextView_Message = 2131492887;
			
			// aapt resource value: 0x7f0c0018
			public const int Widget_WearDiag_TextView_Title = 2131492888;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionLabel = new int[] {
					16842902,
					16842903,
					16842904,
					16842927,
					16843087,
					16843091,
					16843287,
					16843288,
					16843692,
					2130771971,
					2130771972};
			
			// aapt resource value: 8
			public const int ActionLabel_android_fontFamily = 8;
			
			// aapt resource value: 3
			public const int ActionLabel_android_gravity = 3;
			
			// aapt resource value: 6
			public const int ActionLabel_android_lineSpacingExtra = 6;
			
			// aapt resource value: 7
			public const int ActionLabel_android_lineSpacingMultiplier = 7;
			
			// aapt resource value: 5
			public const int ActionLabel_android_maxLines = 5;
			
			// aapt resource value: 4
			public const int ActionLabel_android_text = 4;
			
			// aapt resource value: 2
			public const int ActionLabel_android_textColor = 2;
			
			// aapt resource value: 1
			public const int ActionLabel_android_textStyle = 1;
			
			// aapt resource value: 0
			public const int ActionLabel_android_typeface = 0;
			
			// aapt resource value: 10
			public const int ActionLabel_maxTextSize = 10;
			
			// aapt resource value: 9
			public const int ActionLabel_minTextSize = 9;
			
			public static int[] ActionPage = new int[] {
					16842902,
					16842903,
					16842904,
					16842927,
					16843033,
					16843087,
					16843091,
					16843173,
					16843287,
					16843288,
					16843692,
					16843840,
					16843848,
					2130771971,
					2130771972,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 7
			public const int ActionPage_android_color = 7;
			
			// aapt resource value: 11
			public const int ActionPage_android_elevation = 11;
			
			// aapt resource value: 10
			public const int ActionPage_android_fontFamily = 10;
			
			// aapt resource value: 3
			public const int ActionPage_android_gravity = 3;
			
			// aapt resource value: 8
			public const int ActionPage_android_lineSpacingExtra = 8;
			
			// aapt resource value: 9
			public const int ActionPage_android_lineSpacingMultiplier = 9;
			
			// aapt resource value: 6
			public const int ActionPage_android_maxLines = 6;
			
			// aapt resource value: 4
			public const int ActionPage_android_src = 4;
			
			// aapt resource value: 12
			public const int ActionPage_android_stateListAnimator = 12;
			
			// aapt resource value: 5
			public const int ActionPage_android_text = 5;
			
			// aapt resource value: 2
			public const int ActionPage_android_textColor = 2;
			
			// aapt resource value: 1
			public const int ActionPage_android_textStyle = 1;
			
			// aapt resource value: 0
			public const int ActionPage_android_typeface = 0;
			
			// aapt resource value: 16
			public const int ActionPage_buttonRippleColor = 16;
			
			// aapt resource value: 15
			public const int ActionPage_imageScaleMode = 15;
			
			// aapt resource value: 14
			public const int ActionPage_maxTextSize = 14;
			
			// aapt resource value: 13
			public const int ActionPage_minTextSize = 13;
			
			// aapt resource value: 17
			public const int ActionPage_pressedButtonTranslationZ = 17;
			
			public static int[] BoxInsetLayout_Layout = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int BoxInsetLayout_Layout_layout_box = 0;
			
			public static int[] CircledImageView = new int[] {
					16843033,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int CircledImageView_android_src = 0;
			
			// aapt resource value: 5
			public const int CircledImageView_circle_border_color = 5;
			
			// aapt resource value: 4
			public const int CircledImageView_circle_border_width = 4;
			
			// aapt resource value: 1
			public const int CircledImageView_circle_color = 1;
			
			// aapt resource value: 6
			public const int CircledImageView_circle_padding = 6;
			
			// aapt resource value: 2
			public const int CircledImageView_circle_radius = 2;
			
			// aapt resource value: 3
			public const int CircledImageView_circle_radius_pressed = 3;
			
			// aapt resource value: 8
			public const int CircledImageView_image_circle_percentage = 8;
			
			// aapt resource value: 9
			public const int CircledImageView_image_horizontal_offcenter_percentage = 9;
			
			// aapt resource value: 10
			public const int CircledImageView_image_tint = 10;
			
			// aapt resource value: 7
			public const int CircledImageView_shadow_width = 7;
			
			public static int[] CircularButton = new int[] {
					16843033,
					16843173,
					16843840,
					16843848,
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 1
			public const int CircularButton_android_color = 1;
			
			// aapt resource value: 2
			public const int CircularButton_android_elevation = 2;
			
			// aapt resource value: 0
			public const int CircularButton_android_src = 0;
			
			// aapt resource value: 3
			public const int CircularButton_android_stateListAnimator = 3;
			
			// aapt resource value: 5
			public const int CircularButton_buttonRippleColor = 5;
			
			// aapt resource value: 4
			public const int CircularButton_imageScaleMode = 4;
			
			// aapt resource value: 6
			public const int CircularButton_pressedButtonTranslationZ = 6;
			
			public static int[] DelayedConfirmationView = new int[] {
					2130771987};
			
			// aapt resource value: 0
			public const int DelayedConfirmationView_update_interval = 0;
			
			public static int[] DotsPageIndicator = new int[] {
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000};
			
			// aapt resource value: 3
			public const int DotsPageIndicator_dotColor = 3;
			
			// aapt resource value: 4
			public const int DotsPageIndicator_dotColorSelected = 4;
			
			// aapt resource value: 8
			public const int DotsPageIndicator_dotFadeInDuration = 8;
			
			// aapt resource value: 6
			public const int DotsPageIndicator_dotFadeOutDelay = 6;
			
			// aapt resource value: 7
			public const int DotsPageIndicator_dotFadeOutDuration = 7;
			
			// aapt resource value: 5
			public const int DotsPageIndicator_dotFadeWhenIdle = 5;
			
			// aapt resource value: 1
			public const int DotsPageIndicator_dotRadius = 1;
			
			// aapt resource value: 2
			public const int DotsPageIndicator_dotRadiusSelected = 2;
			
			// aapt resource value: 9
			public const int DotsPageIndicator_dotShadowColor = 9;
			
			// aapt resource value: 11
			public const int DotsPageIndicator_dotShadowDx = 11;
			
			// aapt resource value: 12
			public const int DotsPageIndicator_dotShadowDy = 12;
			
			// aapt resource value: 10
			public const int DotsPageIndicator_dotShadowRadius = 10;
			
			// aapt resource value: 0
			public const int DotsPageIndicator_dotSpacing = 0;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] ProgressSpinner = new int[] {
					2130772001};
			
			// aapt resource value: 0
			public const int ProgressSpinner_color_sequence = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130772014,
					2130772015,
					2130772016,
					2130772017};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			public static int[] WatchViewStub = new int[] {
					2130772002,
					2130772003};
			
			// aapt resource value: 0
			public const int WatchViewStub_rectLayout = 0;
			
			// aapt resource value: 1
			public const int WatchViewStub_roundLayout = 1;
			
			public static int[] WearableFrameLayout = new int[] {
					16843017,
					16843018,
					16843264,
					16843885,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011};
			
			// aapt resource value: 0
			public const int WearableFrameLayout_android_foreground = 0;
			
			// aapt resource value: 2
			public const int WearableFrameLayout_android_foregroundGravity = 2;
			
			// aapt resource value: 3
			public const int WearableFrameLayout_android_foregroundTint = 3;
			
			// aapt resource value: 1
			public const int WearableFrameLayout_android_measureAllChildren = 1;
			
			// aapt resource value: 4
			public const int WearableFrameLayout_layout_gravityRound = 4;
			
			// aapt resource value: 6
			public const int WearableFrameLayout_layout_heightRound = 6;
			
			// aapt resource value: 11
			public const int WearableFrameLayout_layout_marginBottomRound = 11;
			
			// aapt resource value: 8
			public const int WearableFrameLayout_layout_marginLeftRound = 8;
			
			// aapt resource value: 10
			public const int WearableFrameLayout_layout_marginRightRound = 10;
			
			// aapt resource value: 7
			public const int WearableFrameLayout_layout_marginRound = 7;
			
			// aapt resource value: 9
			public const int WearableFrameLayout_layout_marginTopRound = 9;
			
			// aapt resource value: 5
			public const int WearableFrameLayout_layout_widthRound = 5;
			
			public static int[] WearableHeaderTextView = new int[] {
					2130772012,
					2130772013};
			
			// aapt resource value: 0
			public const int WearableHeaderTextView_circular_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int WearableHeaderTextView_circular_text_size = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
